[project]
name = "pandas-tosql-dbx-fix"
version = "1.0.3"
description = "Fix for the Pandas to_sql() dataframe method that fails when we try pushing more than 256 values."
readme = "README.md"
authors = [
    { name = "Tarek Samhan", email = "tsamhan@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "databricks-sqlalchemy>=2.0.8",
    "pandas>=2.3.3",
    "sqlalchemy>=2.0.45",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.scripts]
pandas-tosql-dbx-fix = "pandas_tosql_dbx_fix:main"

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[project.urls]
Homepage = "https://github.com/beefupinetree/pandas-tosql-dbx-fix"
